### ISSUE TITLE
Invalid Debian package name

### ISSUE THREAD

**Issue by laurent-simon** [yatima1460/Drill#73]
When Drill is installed as a Debian package, the reported source package name is  `https://github.com/yatima1460/Drill`. A URL is not a valid package name. This is a problem for tools that need a real package name to work properly.

For example, [debsecan ]( https://packages.debian.org/sid/debsecan) (a classic tool used to scan for vulnerabilities on Debian installations)  cannot work anymore due to this anomaly:

```
$ debsecan --suite $(lsb_release --codename --short) --source https://raw.githubusercontent.com/BBVA/ust2dsa/data/  --format detail
Traceback (most recent call last):
  File "/usr/bin/debsecan", line 1370, in <module>
    rate_system(target, options, fetch_data(options, config), history)
  File "/usr/bin/debsecan", line 1305, in rate_system
    raise SyntaxError(('package %s references '
SyntaxError: package drill-search-gtk references invalid source package 'https://github.com/yatima1460/Drill'
```

So, when Drill is installed, the result is that the overall system cannot be analyzed for security vulnerabilities...

Remark: I agree that `debsecan` should not fail like that. It should report the anomaly, discard Drill from the analysis and continue his work. But all tools that looks for a valid package name are potentially affected by this small mistake.

**Environment:**
* Installation: Debian package
* Version: v566
* OS: Ubuntu 20.10

**Comment by yatima1460** [comment]
Hello, sorry if I abandoned this repo, I hope to revamp it soon

Thanks for posting issues :D
